version: 0.2
phases:
  post_build:
    commands:
      - echo "ACCOUNT_ID=${ACCOUNT_ID}"
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"hello-world","imageUri":"%s"}]' ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/actions/image-repo > imagedefinitions.json
artifacts:
  files:
    - '**/*'
